version: "3.7"

services:
  vue:
    image: "reciplo:latest"
    build: .
    ports:
      - "80:8080"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - "./app:/app:delegated"
      - "/app/node_modules/"
